# Generated by Django 3.0.5 on 2022-02-15 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2022, 2, 15)),
        ),
    ]
